### ISSUE TITLE
SynchronizedLocalAndServerDatabase.java 문제

### ISSUE THREAD

**Issue by dinsslug** [kangjisung/AndroidInven#19]
* 문제 사항 : 어플 실행 시 런타임 오류 발생

```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
at com.example.kangjisung.likeroom.SQLiteDatabaseControl.SimpleDatabaseTest.AddStoreAndCustomerUniqueId(SimpleDatabaseTest.java:165)
at com.example.kangjisung.likeroom.SQLiteDatabaseControl.SynchronizedLocalAndServerDatabase.GetStoreAndCustomerRegisteredInfo(SynchronizedLocalAndServerDatabase.java:67)
at com.example.kangjisung.likeroom.MainActivity.onCreate(MainActivity.java:74)
```

**Comment by stories2** [comment]
This problem causes 541f383ddcc0de7aded99c0e74a63db2704166a7.
Delete app saved file and cache.
